version: "3.9"

services:
  api:
    build:
      context: ./server
    image: rarias1082/first-app-api:latest
    container_name: first-app-api
    ports:
      - "3000:3000"
    networks:
      - appnet

  web:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: rarias1082/first-app-web:latest
    container_name: first-app-web
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
