services:
  api:
    build: ./server
    image: rarias1082/first-app-api:latest
    container_name: first-app-api
    ports:
      - "5000:5000"
    networks: [appnet]

  web:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: rarias1082/first-app-web:latest
    container_name: first-app-web
    depends_on: [api]
    ports:
      - "8080:80"
    networks: [appnet]

networks:
  appnet:
    driver: bridge
